spring.application.name=springbk1
server.port=${PORT:8081}
spring.datasource.url=jdbc:mysql://localhost:3306/springbk1
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# logging.level.root=OFF